### ISSUE TITLE
GLib-GIO-ERROR

### ISSUE THREAD

**Issue by dCosminn** [DevilXD/TwitchDropsMiner#321]
It won't run and getting this error with the latest development build:
```
GLib-GIO-ERROR **: 17:42:45.744: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
Trace/breakpoint trap (core dumped)
```

Ubuntu 22.04.3 LTS, Kernel 6.2 using Wayland
ldd (Ubuntu GLIBC 2.35-0ubuntu3.4) 2.35

**Comment by guihkx** [comment]
This seems to be [an issue with GTK](https://gitlab.gnome.org/GNOME/gtk/-/issues/3680), which has been fixed 2 years ago in GTK 4.

But because we bundle GTK 3 libraries with the app instead, this bug can still be triggered, apparently.

Can you try setting `GDK_BACKEND=x11` before launching the program and see if that works?

**Comment by guihkx** [comment]
Out of curiosity, can you please check if you can reproduce this 'crash' with this AppImage build I've been working on?

https://github.com/guihkx/TwitchDropsMiner/actions/runs/6504674655

Just download the `Twitch.Drops.Miner.Linux.AppImage` artifact at the bottom of the page.

**Comment by dCosminn** [comment]
Yes, using GDK_BACKEND=x11 seems to work. 
For those with the same problem, run in terminal:  GDK_BACKEND=x11 ./Twitch\ Drops\ Miner\ \(by\ DevilXD\)  

> Out of curiosity, can you please check if you can reproduce this 'crash' with this AppImage build I've been working on?
> 
> https://github.com/guihkx/TwitchDropsMiner/actions/runs/6504674655
> 
> Just download the `Twitch.Drops.Miner.Linux.AppImage` artifact at the bottom of the page.

Yep, still getting the error:
` ./Twitch.Drops.Miner-x86_64.AppImage 

(main.py:61183): GLib-GIO-ERROR **: 18:48:47.408: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
Trace/breakpoint trap (core dumped)
`

**Comment by guihkx** [comment]
> Yes, using GDK_BACKEND=x11 seems to work. For those with the same problem, run in terminal: GDK_BACKEND=x11 ./Twitch\ Drops\ Miner\ (by\ DevilXD)

Thank you for confirming it works!

> Yep, still getting the error:
> 
> ```
> ./Twitch.Drops.Miner-x86_64.AppImage 
> 
> (main.py:61183): GLib-GIO-ERROR **: 18:48:47.408: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
> Trace/breakpoint trap (core dumped)
> ```

Thanks for testing.

Thankfully, AppImages are flexible and they allow us to set predefined environment variables with the app, so I'll just set `GDK_BACKEND=x11` by default and that crash should be gone for you. :)

@DevilXD Do you oppose having an AppImage package instead of a PyInstaller binary for Linux?  Or we could keep both...

**Comment by DevilXD** [comment]
No opposition from my side, it's actually better - that way, people can choose which one they'd like to use. The only downside is having to support both going forward, but if that's not a problem for you, it's all good. I'm not sure if I can maintain both of them myself, as I'm not really a Linux guy, besides having a GUI-less VPS to run my Python bot on, and knowing some basic linux commands to go around that.

**Comment by guihkx** [comment]
They aren't *that* different, so supporting both isn't going to be much of an issue.

I'll try to send a PR today!
